# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactstagingdirectoryWeb: 'web'

steps:
- task: NuGetToolInstaller@1
  displayName: Install .NET Tools

- task: NuGetCommand@2
  displayName: Restore Wasm Solution
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@1
  displayName: Build Wasm Client Website
  inputs:
    command: 'build'
    projects: '**/Client/TanglewoodCandleCo.Wasm.Client.csproj'

- task: DotNetCoreCLI@1
  displayName: 'Publish Wasm Client Website'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectoryWeb)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Wasm Web Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectoryWeb)'
  condition: succeededOrFailed()